const productos=[
                       {codigo: 0, nombre: "Hummus 2dm", precio: 1500, stock: 8, tipo: "sustrato" , imagen: "../assets/img/Vivero-001/Vivero/hummus.jpg"},
                       {codigo: 1, nombre: "Hummus 6dm", precio: 3300, stock: 9, tipo: "sustrato", imagen: "../assets/img/Vivero-001/Vivero/hummus.jpg"},
                       {codigo: 2, nombre: "Perlita", precio: 1500, stock: 9, tipo: "sustrato", imagen: "../assets/img/Vivero-001/Vivero/perlita.jpg"},
                       {codigo: 3, nombre: "Tierra cactus", precio: 1600, stock: 3, tipo: "sustrato", imagen: "../assets/img/Vivero-001/Vivero/tierranegra.jpg"},
                       //{codigo: 4, nombre: "Rosas", precio: 5000, stock: 3, tipo: "planta exterior", imagen: "🪴"},
                       //{codigo: 5, nombre: "Rosa iceberg", precio: 3500, stock: 3, tipo: "planta exterior", imagen: "🪴"},
                       //{codigo: 6, nombre: "Santolina", precio: 2800, stock: 1, tipo: "planta exterior", imagen: "🪴"},
                       {codigo: 7, nombre: "Dietes", precio: 4500, stock: 2, tipo: "planta exterior", imagen: "../assets/img/Vivero-001/Vivero/dietes.jpg"},
                       {codigo: 8, nombre: "Lantana", precio: 900, stock: 6, tipo: "planta exterior", imagen: "../assets/img/Vivero-001/Vivero/lantana.jpg"},
                       {codigo: 9, nombre: "Margarita", precio: 800, stock: 1, tipo: "planta exterior", imagen: "../assets/img/Vivero-001/Vivero/margaritas.jpg"},
                       //{codigo: 10, nombre: "Cactus", precio: 1000, stock: 6, tipo: "planta exterior", imagen: "🪴"},
                       {codigo: 11, nombre: "Rosa China", precio: 3000, stock: 4, tipo: "planta exterior", imagen: "../assets/img/Vivero-001/Vivero/rosachina.jpg"},
                       //{codigo: 12, nombre: "Helecho", precio: 5800, stock: 0, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 13, nombre: "Asplenium XL", precio: 7000, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/asplenium.jpg"},
                       //{codigo: 14, nombre: "Begonia XL", precio: 4000, stock: 1, tipo: "Plantas interior", imagen: "🪴"},
                       //{codigo: 15, nombre: "Anturio", precio: 6800, stock: 2, tipo: "Plantas interior", imagen: "🪴"},
                       //{codigo: 16, nombre: "Syngonium rosa", precio: 5000, stock: 1, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 17, nombre: "Syngo. Chocolate", precio: 3400, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/syngochoco.jpg"},
                       {codigo: 18, nombre: "Palo de agua", precio: 3500, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/palodeagua.jpg"},
                       {codigo: 19, nombre: "Maranta", precio: 2800, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/maranta.jpg"},
                       {codigo: 20, nombre: "CLepia", precio: 2600, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/clepia.jpg"},
                       {codigo: 21, nombre: "Syngonium plata", precio: 6000, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/syngoplata.jpg"},
                       {codigo: 22, nombre: "Syngonium rosa", precio: 5500, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/syngorosa.jpg"},
                       {codigo: 23, nombre: "Begonia", precio: 2000, stock: 0, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/begonia.jpg"},
                       //{codigo: 24, nombre: "Palmito", precio: 1800, stock: 1, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 25, nombre: "Alocasia Amazonica", precio: 4000, stock: 0, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/amazonica.jpg"},
                       //{codigo: 26, nombre: "Helecho chico", precio: 4200, stock: 0, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 27, nombre: "Fitonia", precio: 2800, stock: 0, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/fitonia.jpg"},
                       //{codigo: 28, nombre: "Asplenium chico", precio: 1500, stock: 2, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 29, nombre: "Enamorada del muro", precio: 2500, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/enamoradamuro.jpg"},
                       //{codigo: 30, nombre: "Dracena", precio: 5000, stock: 1, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 31, nombre: "Adansonii", precio: 3000, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/adansonii.jpg"},
                       //{codigo: 32, nombre: "Cinta Crespa", precio: 2000, stock: 1, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 33, nombre: "Pilea", precio: 1700, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/peperomia.jpg"},
                       {codigo: 34, nombre: "Peperomia corazon", precio: 2800, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/pilea.jpg"},
                       {codigo: 35, nombre: "Cordatum grande", precio: 4200, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/cordatum.jpg"},
                       //{codigo: 36, nombre: "Cordatum chico", precio: 2500, stock: 1, tipo: "Plantas interior", imagen: "🪴"},
                       //{codigo: 37, nombre: "Asplenium crespo", precio: 2000, stock: 2, tipo: "Plantas interior", imagen: "🪴"},
                       //{codigo: 38, nombre: "Diplodenia", precio: 2500, stock: 2, tipo: "Plantas interior", imagen: "🪴"},
                       //{codigo: 39, nombre: "Peperomia scandens", precio: 3500, stock: 1, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 40, nombre: "Philo. sanguineo", precio: 2500, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/philosanguineo.jpg"},
                       {codigo: 41, nombre: "Philo. Xanadu", precio: 3500, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/philoxanadu.jpg"},
                       {codigo: 42, nombre: "Aralia", precio: 3700, stock: 2, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/aralia.jpg"},
                       //{codigo: 43, nombre: "Philodendron plateado", precio: 3000, stock: 2, tipo: "Plantas interior", imagen: "🪴"},
                       {codigo: 44, nombre: "Peperomia", precio: 2800, stock: 3, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/pepero.jpg"},
                       {codigo: 45, nombre: "Philo. Imperial", precio: 4900, stock: 1, tipo: "Plantas interior", imagen: "../assets/img/Vivero-001/Vivero/philoimperial.jpg"},
]